### ISSUE TITLE
repo does not seem accessible on 1.0.-snapshot

### ISSUE THREAD

**Issue by charroch** [jvoegele/gradle-android-plugin#1]
```
classpath 'com.jvoegele.gradle.plugins:android-plugin:1.0-SNAPSHOT'
```

dependency is missing against the following url:
http://jvoegele.com/maven2/

**Comment by jvoegele** [comment]
1.0-SNAPSHOT is no longer a valid version.  You can use version 0.9.3 (for Gradle 0.9) or 0.8.2 (for Gradle 0.8)

**Comment by jvoegele** [comment]
1.0-SNAPSHOT is no longer a valid version. You can use version 0.9.3 (for Gradle 0.9) or 0.8.2 (for Gradle 0.8)
