### ISSUE TITLE
Simple project following instructions does not build

### ISSUE THREAD

**Issue by johnboy99** [jvoegele/gradle-android-plugin#101]
Hi Everyone,
I am new to gradle and I think I am missing something simple but would appreciate any help that can be given.
I have tried to follow the usage instructions in readme.md for the gradle-android-plugin that consists of the three basic steps...

1) Create new project "MyAndroidApp" from command line using "android" command
2) cd to project MyAndroidApp & create gradle.build
3) Append sourceSets to gradle.build to keep ant build compatability

... but I get a build error. 

Here is the command line I used for step 1)

$ android create project --target 1 --path ./MyAndroidApp --activity MyAndroidActivity --package my.android.package

Created project directory: ./MyAndroidApp
Created directory /var/home/johnp/AndroidApps/MyAndroidApp/src/my/android/package
Added file ./MyAndroidApp/src/my/android/package/MyAndroidActivity.java
Created directory /var/home/johnp/AndroidApps/MyAndroidApp/res
Created directory /var/home/johnp/AndroidApps/MyAndroidApp/bin
Created directory /var/home/johnp/AndroidApps/MyAndroidApp/libs
Created directory /var/home/johnp/AndroidApps/MyAndroidApp/res/values
Added file ./MyAndroidApp/res/values/strings.xml
Created directory /var/home/johnp/AndroidApps/MyAndroidApp/res/layout
Added file ./MyAndroidApp/res/layout/main.xml
Created directory /var/home/johnp/AndroidApps/MyAndroidApp/res/drawable-xhdpi
Created directory /var/home/johnp/AndroidApps/MyAndroidApp/res/drawable-hdpi
Created directory /var/home/johnp/AndroidApps/MyAndroidApp/res/drawable-mdpi
Created directory /var/home/johnp/AndroidApps/MyAndroidApp/res/drawable-ldpi
Added file ./MyAndroidApp/AndroidManifest.xml
Added file ./MyAndroidApp/build.xml
Added file ./MyAndroidApp/proguard-project.txt

... then I changed to the project directory ...

$ cd MyAndroidApp

Here is build.gradle after I perfromed steps 2 & 3 ...

buildscript {
  repositories {
    mavenCentral()
  }

  dependencies {
    classpath 'org.gradle.api.plugins:gradle-android-plugin:1.2.1'
  }
}
apply plugin: 'android'
repositories {
  mavenCentral()
}
sourceSets {
  main {
    java {
      srcDir 'src/java'
    }
  }
}

...  and here is the build error ...

$ gradle clean release
sdkDir = /home/johnp/android-studio-bundle/android-studio/sdk
toolsDir = /home/johnp/android-studio-bundle/android-studio/sdk/tools
platformToolsDir = /home/johnp/android-studio-bundle/android-studio/sdk/platform-tools
[ant:taskdef] Could not load definitions from resource anttasks.properties. It could not be found.

FAILURE: Build failed with an exception.
- Where:
  Build file '/home/johnp/AndroidApps/MyAndroidApp/build.gradle' line: 10
- What went wrong:
  A problem occurred evaluating root project 'MyAndroidApp'.
  
  > Problem: failed to create task or type gettype
  > Cause: The name is undefined.
  > Action: Check the spelling.
  > Action: Check that any custom tasks/types have been declared.
  > Action: Check that any <presetdef>/<macrodef> declarations have taken place.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 5.638 secs
$ 

... can anyone spot what I have done wrong ?
... thanks for any help you can give

**Comment by nflucian** [comment]
I have the same issue.
My system:
Gradle 1.8
Groovy:       1.8.6
Ant:          Apache Ant(TM) version 1.9.2 compiled on July 8 2013
Ivy:          2.2.0
JVM:          1.7.0_25 (Oracle Corporation 23.7-b01)
OS:           Linux 3.8.0-31-generic amd64 - Ubuntu 12.04

Android SDK: http://dl.google.com/android/android-sdk_r22.2.1-linux.tgz

Also I tried with Gradle 1.7 and Java 6.

**Comment by OsBelief** [comment]
I have the same issue,please help me.

**Comment by pmalek** [comment]
Same here with `gradle 1.12`
