### ISSUE TITLE
The plugin should use the environment to read the SDK dir

### ISSUE THREAD

**Issue by mttkay** [jvoegele/gradle-android-plugin#16]
It seems that the plugin requires a local.properties file to exist carrying the path to the Android SDK. This makes it very difficult to use this plugin with build servers, since that file cannot be checked in to the source code control (it's machine specific).

Instead, why not read the ANDROID_HOME environment variable?

**Comment by fdasoghe** [comment]
Yes, I agree. I was thinking about implementing more than one method, and trying them in a well-defined sequence (like the i18n resource's resolution mechanism in Java).

Now I'm focused on Gingerbread compatibility... is this issue very important for you?

And, another question/curiosity: are you using a CI server to build an Android project?

**Comment by mttkay** [comment]
Not that important just now, but will probably become, soon. We use Hudson as a CI server, but we're still relying on Maven2 to build the app. I'm currently evaluating alternative build systems, and Gradle seems to be the perfect platform to arrive at the kind of flexibility we're looking for. Maven is such a pain to extend, and its dependency model is overkill for us (for instance, we'd prefer a plain old lib/ folder that's under revision control).

I'd be happy to provide a patch for this when I get to it. At the moment I'm still getting into Gradle head-first, but I'm very pleased with what I've seen so far, and I have some background in Grails+Groovy, so I'll be able to quickly get into some coding.

Thanks again for running this project, I'm really excited about it!

**Comment by fdasoghe** [comment]
Well, your thanks should go to Jason which is the author/founder of this project. I'm an addicted user/recently added contributor :o)

I'm personally very interested in using a continuous integration server in my Android development, from this my question. As I said, my priority is Gingerbread support, after that I'll fix your issue (if Jason will not have already fixed).

If you want to surf on the code and make a build, feel free to ask how, if you need.

Cheers,

Fabio

**Comment by mttkay** [comment]
Great, thanks a lot.

**Comment by fdasoghe** [comment]
Work done. In the android_home branch. I have no time left now but I'll update the README as soon as possible, and I'll ask Jason to review my commit in order to have a new release (0.9.6 or something like that).

Enjoy,

Fabio

**Comment by jvoegele** [comment]
I'll push out a 0.9.6 release that includes the fix.

**Comment by fdasoghe** [comment]
It works for me. Could this issue be closed?

**Comment by mttkay** [comment]
I'm sorry, I hadn't yet had a chance to double check it (I halted work on Gradle integration  for our project to wait for your Gingerbread fix, until then I can't really do anything with it).

But, sure, feel free to close if you say you fixed it.

**Comment by fdasoghe** [comment]
Ok. Tomorrow I'll work on it (Gingerbread compatibility), I cannot promise I'll finish it but I'll do a significant advance.

**Comment by mttkay** [comment]
You guys rock.

**Comment by fdasoghe** [comment]
As you see, Ladicek was faster then me. I'll do some further testing, in the meantime I think Jason will do the merge (and a new release).

**Comment by fdasoghe** [comment]
This patch works for all who have tested, nobody complains, I close the issue :o)
