### ISSUE TITLE
All plugin tasks should be grouped into an 'Android' task group

### ISSUE THREAD

**Issue by mttkay** [jvoegele/gradle-android-plugin#24]
Right now, if you run `gradle tasks`, all Android related tasks show up as "other". This is quite messy. I vote for having all tasks exposed by gradle-android-plugin be assigned the 'Android' group, i.e. for all tasks we should `task.group = "Android"`.

**Comment by fdasoghe** [comment]
I agree, but... why we're still using issue tracker on GitHub? Haven't we moved all this on Google Code? (Maybe we should close the issue tracker here on GitHub so it's not possible to post in the wrong place).

**Comment by mttkay** [comment]
true -- my bad. I'll re-submit it on Google Code. And yes, I agree we should close the issue tracker here.
