### ISSUE TITLE
Support multiple resource directories in aapt

### ISSUE THREAD

**Issue by shawnlauzon** [jvoegele/gradle-android-plugin#45]
The aapt command-line tool supports multiple resource directories with the -S argument:

>   -S  directory in which to find resources.  Multiple directories will be scanned
>      and the first match found (left to right) will take precedence.

and as part of the aapt p[ackage] command: `[-S resource-sources ...]]`

In ant, this is done by nested <res path=""> elements

**Comment by ealden** [comment]
Closing this, as PR #57 solves this.
