### ISSUE TITLE
Modify manifest package name with aapt

### ISSUE THREAD

**Issue by shawnlauzon** [jvoegele/gradle-android-plugin#46]
The Android SDK just had a patch submitted for [Issue 21366](http://code.google.com/p/android/issues/detail?id=21336), support for `--rename-manifest-package`. It would be nice to support this when it's part of the main SDK tools (perhaps r17)

**Comment by ealden** [comment]
@shawnlauzon this was added in the original #47 which we broke down into smaller PRs for focus.  Are you planning to provide another PR to address this issue?

**Comment by shawnlauzon** [comment]
Hello! Sorry about the long delay :( I just moved to New York and had other things on my mind.

As for this item: I have it finished and separated out a couple months ago, but unfortunately was not able to build an integration test that works. The major problem is that the forked compiler doesn't display any debug information, and I can't figure out how to disable forking for the integration test. Thus I always get:

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':compileIntegrationTestGroovy'.
  > Forked groovyc returned error code: 1

Thoughts on how to de-fork the integration test are welcome, otherwise I'm stuck.

**Comment by ealden** [comment]
@shawnlauzon do you reach the point wherein it creates a test result inside `build/reports/tests`?

**Comment by shawnlauzon** [comment]
Well, it does create an index.html file, but it doesn't have anything in it: 0 tests, 0 failures

**Comment by jaypatrickhoward** [comment]
Hey Shawn.  This may be outside the scope of this issue, but it would be nice if the plugin also supported modifying additional items in the manifest that need to reference the app package.  This becomes relevant when an app uses GCM for cloud messaging.  Per Google's instructions, such apps need to create permissions and broadcast receivers that reference the app package.  Instructions here:

http://developer.android.com/guide/google/gcm/gs.html

**Comment by jaypatrickhoward** [comment]
Bleh.  Nevermind. I didn't realize this ticket is just to extend the plugin to support a new(ish) aapt option.  Aapt doesn't seem to do what I need it to do, so there's nothing to be done here w.r.t. to the gradle android plugin.

**Comment by shawnlauzon** [comment]
@jaypatrickhoward Yeah you're right, I don't see a way to do that in aapt.
I've looked into updating the aapt ant plugin, but not aapt itself; not
sure if it's something that can be updated in the source directly.

On Thu, Jul 5, 2012 at 7:49 PM, jaypatrickhoward <
reply@reply.github.com
