### ISSUE TITLE
Android Scala code not packaging properly

### ISSUE THREAD

**Issue by MarcinGil** [jvoegele/gradle-android-plugin#48]
I've created a simple project containing single activity in src/main/scala/MainActivity.scala containing nothing but onCreate() that loads a layout.

Based on documentation I've created `build.gradle`:

```
apply plugin: 'scala'

/// For Android plugin
buildscript {
    repositories {
        mavenCentral()
    }

    dependencies {
        classpath 'org.gradle.api.plugins:gradle-android-plugin:1.1.0'
    }
}

apply plugin: 'android'

repositories {
    maven {
        url = "http://scala-tools.org/repo-releases/"
    }
}

dependencies {
    scalaTools 'org.scala-lang:scala-library:2.9.1'
    scalaTools 'org.scala-lang:scala-compiler:2.9.1'
    compile 'org.scala-lang:scala-library:2.9.1'
}

sourceSets {
    main {
        scala {
            srcDir 'src'
        }
    }
}

version = "0.1"

androidSignAndAlign {
    keyStore = "~/.android/debug.keystore"
    keyAlias = "androiddebugkey"
    keyStorePassword = "android"
    keyAliasPassword = "android"
}

processResources {
    expand (project.properties)
}

task configureDebug << {
    jar.classifier = "debug"
    proguard.enabled = false
}
```

Executing `gradle configureDebug assemble` gives:

gradle configureDebug assemble
fileTree(Closure) is a deprecated method. Use fileTree((Object){ baseDir }) to have the closure used as the file tree base directory
:configureDebug
:androidProcessResources UP-TO-DATE
:compileJava UP-TO-DATE
:compileScala UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar UP-TO-DATE
:proguard SKIPPED
:androidPackage
[ant:apply] 
[ant:apply] trouble writing output: No expanded opcode for 6a195661 App.scala:60@0001: invoke-direct v0:NffffLscala/App$$anonfun$main$1;, scala.runtime.AbstractFunction1.<init>:()V

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':androidPackage'.
  > apply returned: 2

`gradle -v`

```
Gradle 1.0-milestone-8

Gradle build time: poniedziałek, 13 luty 2012 23:53:32 UTC
Groovy: 1.8.4
Ant: Apache Ant(TM) version 1.8.2 compiled on December 20 2010
Ivy: 2.2.0
JVM: 1.6.0_26 (Sun Microsystems Inc. 20.1-b02)
OS: Linux 3.0.0-16-generic amd64
```

**Comment by ealden** [comment]
Thanks for the bug report.  Haven't used 1.0-milestone-8 with Gradle Android projects so we'll see what can be done to fix this.

**Comment by trombonehero** [comment]
This looks a lot like trouble I had with Dalvik's 64k method limit (which is easy to hit when you include the Scala library). There are [several](http://code.google.com/p/android/issues/detail?id=7147) [bug](http://code.google.com/p/android/issues/detail?id=15603) [reports](http://code.google.com/p/android/issues/detail?id=20814) about this behaviour, and I have submitted a [new bug report about the poor diagnostic message](http://code.google.com/p/android/issues/detail?id=26203).

In the meantime, you might try enabling proguard, since it is good at stripping unused methods.

**Comment by ealden** [comment]
@dentharg does @trombonehero's suggestion work for you?

**Comment by MarcinGil** [comment]
Hi, no it didn't. I've upgraded now to gradle-1.0-rc-3 and have java NullPointerException on line "apply plugin: 'android'".

**Comment by ealden** [comment]
@dentharg the problem with 1.0-rc-3 is separate (#51).  Will have to resolve this first so we can isolate if Scala handling works.
