### ISSUE TITLE
Missing resources and assets in generated apk

### ISSUE THREAD

**Issue by fdasoghe** [jvoegele/gradle-android-plugin#5]
I'm using the proguard-work version of the plugin, building my apk with
    proguard.enabled = false

All seems ok but my application doesn't work, while the very same application launched from the ADT runs correctly.

Watching the content of the two apks shows some difference.

The apk generated by the ADT contains:

```
AndroidManifest.xml
assets
classes.dex
clowai-build.properties
META-INF
res
resources.arsc
```

while the apk generated with command "gradle assemble" is:

```
AndroidManifest.xml
classes.dex
META-INF
res
resources.arsc
```

I followed the layout described in the wiki, so my project is:

```
AndroidManifest.xml
assets/
build/
build.gradle
default.properties
gen/
local.properties
res/
src/
    main/java/
        com/...
    main/resources/
        clowai-build.properties
tools/
```

The Gradle build misses my resource file (in /src/main/resources) and the whole assets directory (which in my case has some content).

Am I doing something wrong (maybe I have to do some more configuration in order to teach gradle where are my Android resources)?

Thanks,

Fabio

**Comment by fdasoghe** [comment]
Mmmh... digging a bit into this, there are two considerations.

1) The "standard" resources, i.e. those into the src/main/resources directory, are actually packed by the jar task into the [projectname].jar file in build/libs directory. So maybe they get their way into the final apk, at last (I didn't verified this yet).

2) An assets folder is actually passed to the AaptExecTask, via the "assets" parameter to aaptexec Ant task (file AaptExecTask.java). But the value is set to androidConvention.assetsDir, which is new File(project.buildDir, 'assets').

I created my Android project using ADT, which create the assets directory on the root of the project. And nobody in the Gradle build process take care of copying assets from here (/assets) to there (/build/assets).

I think the Android standard, both from ADT and from the "android" command line sdk tool, was to create the assets directory on the root, so maybe we have to adhere to this convention?

Cheers,

Fabio

**Comment by fdasoghe** [comment]
I tried to do the modification written above: changing the value of assetsDir in AndroidPluginConvention. It works for me in my test project.

Here it is the (quite trivial, indeed) git patch, applicable on the proguard-work branch:

```
diff --git a/src/main/groovy/com/jvoegele/gradle/plugins/android/AndroidPluginConvention.groovy b/src/main/groovy/com/jvoegele/gradle/plugins/android/AndroidPluginConvention.groovy
index bd5e952..2a00ece 100644
--- a/src/main/groovy/com/jvoegele/gradle/plugins/android/AndroidPluginConvention.groovy
+++ b/src/main/groovy/com/jvoegele/gradle/plugins/android/AndroidPluginConvention.groovy
@@ -15,7 +15,7 @@
     this.project = project
     resDir = new File(project.projectDir, 'res')
     genDir = new File(project.buildDir, 'gen')
-    assetsDir = new File(project.buildDir, 'assets')
+    assetsDir = new File(project.projectDir, 'assets')
     nativeLibsDir = new File(project.projectDir, 'libs')
     androidManifest = new File(project.projectDir, 'AndroidManifest.xml')
     intermediateDexFile = new File(project.buildDir, "classes.dex")
```

The other problem seems a little more serious: it's true that the resource files get packed in the jar file (classes.min.jar), but it doesn't work (the application is unable to find it).

I have a little example project to demonstrate this: it works if built and launched from the ADT, it fails if built from gradle-android-plugin. I can send it to you if you want.

I think this issue is important as it still prevents the plugin to create a working apk for a real-world application (one which uses assets and custom resources). Unless I'm missing some other simpler way to get the files in the right place, of course.

**Comment by fdasoghe** [comment]
I digged another bit (well, a lot, actually) on the /src/main/resources issue.

The dx tool doesn't insert the properties file in the .dex archive, or the apkbuilder takes only the compiled classes from it.
Besides that, I discovered that aapt doesn't get involved in the apk creation: the final work is of apkbuilder (the ant task).

So I tried a little modification in ApkBuilderTask_r7: I added the line

```
sourcefolder(path: project.sourceSets.main.classesDir)
```

in the ant.apkbuilder call.

It works smooth for me :o)

And I hope that is the right thing to do to be aligned with Gradle convention and working.

Do you think it's a good modification to be included in the master branch?

Cheers,

Fabio

**Comment by jvoegele** [comment]
Thanks for the great analysis and the patches.  I have applied both of them on proguard-work branch.

**Comment by fdasoghe** [comment]
Pulled and verified, it works for me, so this issue can be closed.
