### ISSUE TITLE
Compile fails when using r17 @TargetApi annotation

### ISSUE THREAD

**Issue by shawnlauzon** [jvoegele/gradle-android-plugin#54]
This annotation is included in the r17 SDK drop. When I try to build with this, I get an error:

```
package android.annotation does not exist
```

This is because the annotations are in a separate jar file $SDK_HOME/tools/support/annotations.jar. For some reason, this is not part of the classpath.

I'm not sure how to fix this; the ant script seems to be updated (in NewSetupTask.java), since it displays this when I enable --debug:

```
API<=15: Adding annotations.jar to the classpath.
```

However, the build seems to use a different classpath from that setup in NewSetupTask.java (note that android.jar is included here):

```
'-classpath'
'/Users/Mac/Codez/workspace/Malauzai-trunk/build/classes/main:/Users/Mac/Codez/workspace/Malauzai-trunk/libs/jackson-core-asl-1.9.2.jar:/Users/Mac/Codez/workspace/Malauzai-trunk/libs/jackson-mapper-asl-1.9.2.jar:/Users/Mac/Codez/workspace/Malauzai-trunk/libs/android-support-v4.jar:/Users/Mac/Codez/android-sdk-mac_x86/platforms/android-9/android.jar:/Users/Mac/Codez/android-sdk-mac_x86/add-ons/addon_google_apis_google_inc_9/libs/maps.jar'
```

So, I don't understand enough about how the classpath is setup in Gradle. If anyone could provide some light on how this classpath gets set, I can fix the problem.

**Comment by kevinmcmahon** [comment]
Just a quick note to those looking to work around this until the classpath can be set properly. You can add a compile dependency in your project's build.gradle file to the annotations.jar and this will resolve the build error.

**Comment by jvoegele** [comment]
I think the 1.2.0 release has resolved this issue. Can you confirm?
