### ISSUE TITLE
dx invocation fails on with ProGuard disabled

### ISSUE THREAD

**Issue by marcusb** [jvoegele/gradle-android-plugin#7]
When ProGuard is disabled in the build script with
  proguard.enabled = false
building fails with the following error:

2:10:12.032 [main] DEBUG o.g.a.i.p.ant.AntLoggingAdapter - Execute:Java13CommandLauncher: Executing '/home/marcus/android-sdk-linux_86/platforms/android-8/tools/dx' with arguments:
'--dex'
'--output=/home/marcus/lucy/lucy-android/build/classes.dex'

The ' characters around the executable and arguments are
not part of the command.
12:10:12.271 [Thread-5] INFO  o.g.a.i.p.ant.AntLoggingAdapter - [ant:apply] no input files specified

This is not surprising considering that the input files are commented out in AndroidPlugin.groovy:

  private void androidPackage(ant, boolean sign) {
    logger.info("Converting compiled files and external libraries into ${androidConvention.intermediateDexFile}...")
    ant.apply(executable: ant.dx, failonerror: true, parallel: true) {
      arg(value: "--dex")
      arg(value: "--output=${androidConvention.intermediateDexFile}")
      if (verbose) arg(line: "--verbose")
      //arg(path: project.sourceSets.main.classesDir)
      fileset(file: proguardTask.outJar)
    }

I'm using Android SDK 2.2.

**Comment by fdasoghe** [comment]
That is odd... for what I know, that task uses the jar produced by the previous task (proguard if enabled, jar if proguard if disabled, as your case).

What version of gradle-android-plugin are you using?

**Comment by fdasoghe** [comment]
I can confirm: I get the problem with Android SDK 2.2 (r07), building against platform-7, with latest maintenance release (0.9.4) of gradle-android-plugin.

But this was already discussed in the issue #4: Jason (author of this plugin) has already created a fix, that has still to be committed to the ufficial release.

If you are in a hurry, you can clone the proguard-work branch and build for yourself (or I can send to you the patched version).

**Comment by marcusb** [comment]
Thanks, I can build the version myself if needed. For the moment I've applied  your workaround from #4 (archiveName = proguard.outJar.name), but this gives me:

Execution failed for task ':androidPackageDebug'.
Cause: com.android.apkbuilder.ApkBuilder$ApkCreationException: /home/marcus/myapp/libs is not a folder

I'm using version 0.9.4 of the plugin.

**Comment by marcusb** [comment]
That was with Android SDK Tools version 6. It works with v7. Everything seems ok now with the ProGuard workaround.
