### ISSUE TITLE
Can't sign app using JDK 7

### ISSUE THREAD

**Issue by magnomp** [jvoegele/gradle-android-plugin#70]
As said on Android Developers (http://developer.android.com/tools/publishing/app-signing.html):
"As of JDK 7, the default signing algorithim has changed, requiring you to specify the signature and digest algorithims (-sigalg and -digestalg) when you sign an APK."

Looking at src/main/groovy/com/jvoegele/gradle/tasks/android/AndroidSignAndAlignTask.groovy, I see it does not use the -sigalg and -digestalg parameters. 

The Ant SignJar task does support this parameters through it's "sigalg" and "digestalg" parameters.

Probably it's just a matter of change signWithProvidedKey() and signWithDebugKey(). I could submit a patch but I doesn't know how to work with git, but here are my version of these methods:
private void signWithDebugKey() {
    logger.info("Signing final apk with debug key...")

```
project.ant.signjar(
    jar: unsignedArchivePath.absolutePath,
    signedjar: buildUnalignedArchivePath().absolutePath,
    keystore: retrieveDebugKeystore(),
    storepass: 'android',
    alias: 'androiddebugkey',
    keypass: 'android',
    sigalg: 'MD5withRSA',
    digestalg: 'SHA1',
    verbose: verbose)
```

  }

  private void signWithProvidedKey() {
    if (!getKeyStorePassword() || !getKeyAliasPassword()) {
      def console = System.console()
      keyStorePassword = new String(console.readPassword(
          "Please enter keystore password (store:${keyStore}): "))
      keyAliasPassword = new String(console.readPassword(
          "Please enter password for alias '${keyAlias}': "))
    }

```
logger.info("Signing final apk...")

project.ant.signjar(
    jar: unsignedArchivePath.absolutePath,
    signedjar: buildUnalignedArchivePath().absolutePath,
    keystore: getKeyStore(),
    storepass: getKeyStorePassword(),
    alias: getKeyAlias(),
    sigalg: 'MD5withRSA',
    digestalg: 'SHA1',
    keypass: getKeyAliasPassword(),
    verbose: verbose)
```

  }

**Comment by magnomp** [comment]
I did a pull request (hope I did it correctly) with a change that worked for me

**Comment by forgemo** [comment]
I tried magnomp's patch (without reviewing it) and it solved the issue for me. Thanks magnomp!
