### ISSUE TITLE
All integration tests fail 

### ISSUE THREAD

**Issue by klassm** [jvoegele/gradle-android-plugin#72]
.. and building produces a 

> Problem: failed to create task or type gettype
>   Cause: The name is undefined.
>   Action: Check the spelling.
>   Action: Check that any custom tasks/types have been declared.
>   Action: Check that any <presetdef>/<macrodef> declarations have taken place.

**Comment by joemccall86** [comment]
I had this same problem on our CI server. It went away when I updated the android SDK. I couldn't find any other details, sorry.
