### ISSUE TITLE
javadoc generation needs android.jar on classpath

### ISSUE THREAD

**Issue by marcusb** [jvoegele/gradle-android-plugin#8]
To generate javadocs for my project, I needed the following in the build script:
  javadoc.classpath += files(ant.'android.jar')

It would be better ot have the plugin do this.

**Comment by jvoegele** [comment]
Fixed by https://github.com/jvoegele/gradle-android-plugin/commit/4a34b1df604be2619b3a1a16d0619e76cfd31780
