### ISSUE TITLE
Issue with androidSignAndAlign

### ISSUE THREAD

**Issue by ethankhall** [jvoegele/gradle-android-plugin#80]
There is an issue with signing APKs. When I run `gradle configureDebug assemble` I get the error `Execution failed for task ':androidSignAndAlign'.`

Here is a gist of my logs: https://gist.github.com/3850320
Please let me know if you want any more info. I have a fix for the issue, let me know and I will submit a pull request.

**Comment by georgepapas** [comment]
Hi, what was your fix? I have an issue whereby the androidSignAndAlign never returns.  It hangs waiting for the process.waitFor() to return, which never happens.  Not sure why this is ocurring.  I can manually run the generated jar sign command without issue, and putting this into a groovy script also works without issue.

Cheers

**Comment by ethankhall** [comment]
Here is the diff that I have created. I am going to fork and request a pull. Here is the patch that I have created that fixes the issue. https://raw.github.com/gist/3850320/a7e001493ca21ec2a34dd1329a25687c682eb6a7/patch%20to%20fix%20the%20issue
