### ISSUE TITLE
should allow setting signing password through system property

### ISSUE THREAD

**Issue by marcusb** [jvoegele/gradle-android-plugin#9]
Prompting for passwords on the console does not work in an automated build environment.

**Comment by fdasoghe** [comment]
As I described in issue #13, I've written an implementation on my fork that let you supply the keystore credential in every manner Gradle supports (they are properties of the androidPackage task so you can set them in Gradle standard way).

I hope it will be merged in the master branch as soon as possible, stay tuned!

Cheers,

Fabio

**Comment by fdasoghe** [comment]
Fixed in 0.9.5. See the README.txt for instructions.
