### ISSUE TITLE
Aapt not crunching images

### ISSUE THREAD

**Issue by joemccall86** [jvoegele/gradle-android-plugin#94]
If a project has images that were modified using draw9patch, they aren't "crunched" by aapt and therefore get stretched in the built APK. In AaptExecTask_r21.groovy nocrunch is hard-coded to true, and I think it should be configurable. The issue probably exists in the other AaptExecTask_rXX.groovy files as well.

**Comment by cbartsch** [comment]
Just saw this, it's the same as the one created by me.

**Comment by joemccall86** [comment]
Hey, so to workaround this issue I had to modify a source file to hard-code `nocrunch` to false. It's in [this](https://github.com/joemccall86/gradle-android-plugin/commit/25a564978694a0e8d7d6df34183a9047f539d200) revision on my fork of the repo. If you can compile from source, feel free to [clone my fork](https://github.com/joemccall86/gradle-android-plugin) and get a copy that works around this issue. It should be up-to-date as of writing this comment.

I would make it a pull request but I think the correct solution is to not hard-code it at all. When I get some free cycles I plan on contributing a patch :-)

**Comment by joemccall86** [comment]
Oops, hit the wrong button.

**Comment by cbartsch** [comment]
Thanks, I also already did that and it's working for me.
