### ISSUE TITLE
Problem with 9-patch images and newest gradle-android plugin

### ISSUE THREAD

**Issue by cbartsch** [jvoegele/gradle-android-plugin#96]
With the newest version (1.2.2-SNAPSHOT) and the newest Android SDK (21.0.1), when you build an APK with androidPackage, the 9-patch images don't work anymore.

It seems the 9-patch images have to be processed in some way before being packed into the APK, because when you create an APK with eclipse, the borders with the patches are gone in the archive, but with the gradle plugin they aren't.

**Comment by cbartsch** [comment]
It has been working previously with gradle-android-plugin 1.1.0 and an older Android SDK. Was something changed?

**Comment by fdasoghe** [comment]
You're totally right.
To anyone interested, the missing processing step is the resource crunching, and in the 1.2.2-SNAPSHOT version it's bypassed.
To activate it, you need to modify source file com.jvoegele.gradle.tasks.android.AaptExecTask_r21, line 65, from:

```
nocrunch: true,
```

to

```
nocrunch: false,
```
